version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Pixidream"
    reviewers:
      - "Pixidream"
    commit-message:
      prefix: "ğŸ“¦ï¸ update(dependabot): "
      include: "scope"
    target-branch: "dev"
